### ISSUE TITLE
Could not notify the extension as the lambda span is null or no sampling priority has been found

### ISSUE THREAD

**Issue by tridib041987** [DataDog/dd-trace-java#4637]
Hello

Getting this error on cold start for a lambda, subsequent calls don't have this error. This error started 2 or 3 days back.

We are using dd-agent to publish our logs to DD. Service developed on Java, Spring Boot, AWS Lambda. 
Tracing is done through dd-trace layer (6) and datadog extension(27).

Can someone please help me on whats going on and the way to fix it?

Cloudwatch Logs- 
[dd.trace 2023-02-01 22:34:51:288 +0000] [main] ERROR datadog.trace.lambda.LambdaHandler - could not notify the extension as the lambda span is null or no sampling priority has been found

Tracer Configuration from Logs -
{
    "version": "0.105.0~1afb5a62da",
    "os_name": "Linux",
    "os_version": "4.14.255-296-236.539.amzn2.x86_64",
    "architecture": "amd64",
    "lang": "jvm",
    "lang_version": "11.0.14.1",
    "jvm_vendor": "Amazon.com Inc.",
    "jvm_version": "11.0.14.1+10-LTS",
    "java_class_version": "55.0",
    "http_nonProxyHosts": "null",
    "http_proxyHost": "null",
    "enabled": true,
    "service": "service-dev",
    "agent_url": "http://localhost:8126",
    "agent_error": false,
    "debug": false,
    "analytics_enabled": false,
    "sampling_rules": [
        {},
        {}
    ],
    "priority_sampling_enabled": true,
    "logs_correlation_enabled": true,
    "profiling_enabled": false,
    "appsec_enabled": false,
    "dd_version": "0.105.0~1afb5a62da",
    "health_checks_enabled": false,
    "configuration_file": "no config file present",
    "runtime_id": "7eb221b1-c33c-4cb4-bc46-c163ddc1ce74",
    "logging_settings": {
        "levelInBrackets": false,
        "dateTimeFormat": "'[dd.trace 'yyyy-MM-dd HH:mm:ss:SSS Z']'",
        "logFile": "System.err",
        "configurationFile": "simplelogger.properties",
        "showShortLogName": false,
        "showDateTime": true,
        "showLogName": true,
        "showThreadName": true,
        "defaultLogLevel": "INFO",
        "warnLevelString": "WARN",
        "embedException": false
    },
    "cws_enabled": false,
    "cws_tls_refresh": 5000
}

**Comment by tridib041987** [comment]
Got it solved with upgrading the trace and extension version to the latest.

**Comment by miguelaferreira** [comment]
@tridib041987 What versions are you using? 

I'm using extension `public.ecr.aws/datadog/lambda-extension:44` with version `1.16.2` of `com.datadoghq:dd-trace-api` and `com.datadoghq:dd-trace-ot`, but still get that same error message.
